version: 0.2
env:
  variables:
    BUILD_VERSION: "1.0.0"
    AWS_REGION: "ap-southeast-1"
    ECR_REPO: "576694912472.dkr.ecr.ap-southeast-1.amazonaws.com"
    #    DOCKERFILE_commons: "./quarkushop-commons/Dockerfile"
    DOCKERFILE_customer: "./quarkushop-customer/src/main/docker/Dockerfile.native"
    DOCKERFILE_order: "./quarkushop-order/src/main/docker/Dockerfile.native"
    DOCKERFILE_product: "./quarkushop-product/src/main/docker/Dockerfile.native"
    DOCKERFILE_user: "./quarkushop-user/src/main/docker/Dockerfile.native"

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO

  build:
    commands:
      - ls

      # Build and push each app using app_name variable
      - |
        apps=("quarkushop-customer" "quarkushop-order" "quarkushop-product" "quarkushop-user")
        for app_name in "${apps[@]}"; do
          cd "$app_name";
          docker build -t "$ECR_REPO/$app_name:latest" -f "${!DOCKERFILE_$app_name}" .;
          docker push "$ECR_REPO/$app_name:latest";
          cd ..;
        done

  post_build:
    commands:
      # Deploy to ECS
      - bash deploy-ecs.sh

artifacts:
  files: []
