version: 0.2
env:
  variables:
    BUILD_VERSION: "1.0.0"
    AWS_REGION: "ap-southeast-1"

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 576694912472.dkr.ecr.ap-southeast-1.amazonaws.com

  build:
    commands:
      - ls
      # Build and push quarkusshop-common
      - cd ../quarkushop-common
      - docker build -t YOUR_ECR_REPO_URL_COMMON:latest .
      - docker push YOUR_ECR_REPO_URL_COMMON:latest

      # Build and push quarkushop-customer
      - cd ../quarkushop-customer
      - docker build -t YOUR_ECR_REPO_URL_CUSTOMER:latest .
      - docker push YOUR_ECR_REPO_URL_CUSTOMER:latest

      # Build and push quarkusshop-order
      - cd ../quarkushop-order
      - docker build -t YOUR_ECR_REPO_URL_ORDER:latest .
      - docker push YOUR_ECR_REPO_URL_ORDER:latest

      # Build and push quarkusshop-product
      - cd ../quarkushop-product
      - docker build -t YOUR_ECR_REPO_URL_PRODUCT:latest .
      - docker push YOUR_ECR_REPO_URL_PRODUCT:latest

      # Build and push quarkusshop-user
      - cd ../quarkushop-user
      - docker build -t YOUR_ECR_REPO_URL_USER:latest .
      - docker push YOUR_ECR_REPO_URL_USER:latest
  post_build:
    commands:
      # Deploy to ECS
      - bash deploy-ecs.sh
artifacts:
  files: []
