version: 0.2
env:
  variables:
    BUILD_VERSION: "1.0.0"
    AWS_REGION: "ap-southeast-1"
    ECR_REPO: "576694912472.dkr.ecr.ap-southeast-1.amazonaws.com"

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO

  build:
    commands:
      - ls

      # Build and push each app using app_name variable
      - for app_name in quarkushop-commons quarkushop-customer quarkushop-order quarkushop-product quarkushop-user; do
          cd "$app_name";
          docker build -t "$ECR_REPO/$app_name:latest" .;
          docker push "$ECR_REPO/$app_name:latest";
          cd ..;
        done
  post_build:
    commands:
      # Deploy to ECS
      - bash deploy-ecs.sh
artifacts:
  files: []
