apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkushop-customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkushop-customer
  template:
    metadata:
      labels:
        app: quarkushop-customer
    spec:
      containers:
        - name: quarkushop-customer
          image: YOUR_ECR_REGISTRY_URL/quarkushop-customer:latest
          ports:
            - containerPort: 8080
